### ISSUE TITLE
No data fo direct image or video urls

### ISSUE THREAD

**Issue by novill** [gottfrois/link_thumbnailer#101]
Hello!

Your gem perfectly extracts parameters for embedded images and videos from html page.
But it does nothing if it gets direct image or video url. (

Now it returns empty answer
```

2.2.3 :024 > LinkThumbnailer.generate 'https://www.google.ru/textinputassistant/tia.png'
 => #<LinkThumbnailer::Models::Website:0x0000000cecc028 @images=[], @videos=[], @url=#<URI::HTTPS https://www.google.ru/textinputassistant/tia.png>, @title="", @description="PNG"> 
```

It would be great If it could fill images array with source image data. The same for videos .

I've read your code carefully and understand what changes I need to do. Almost :)

At first I should allow these content types in processor

```
    def valid_response_format?(response)
     ...
+      return true if response['Content-Type'] =~ /image\// 
+      return true if response['Content-Type'] =~ /video\// 
      false
    end
```

When processor.perform_request finished, we have all information in response variable.

After it gem uses response.body, sends it to Nokogiri and analyze its answer with scrappers.

But here it is necessary only to build ::LinkThumbnailer::Models::Website and fill one element with ImageSize or VideoInfo data.

Please help, how to add this update and keep basic gem logic clear.

**Comment by gottfrois** [comment]
Why don't you use my other gem directly? :)

```
r2.3.1 :001 > require 'image_info'
 => true
2.3.1 :002 > image = ImageInfo.from('https://www.google.ru/textinputassistant/tia.png').first
 => #<ImageInfo::Image:0x007ff93bb77028 @uri=#<URI::HTTPS https://www.google.ru/textinputassistant/tia.png>, @width=27, @height=23, @type=:png>
2.3.1 :003 > image.width
 => 27
2.3.1 :004 > image.height
 => 23
2.3.1 :005 > image.type
 => :png
```

**Comment by novill** [comment]
In this case I request data twice.
1. to get content-type to decide what parser to use
2. to parse data

It takes time and some servers temporary ban me

**Comment by gottfrois** [comment]
Right I see! In addition to your changes in the `valid_response_format?` method, have you tried disabling other attributes parsing in the configuration?

```
LinkThumbnailer.generate(url, scrapers: [:default], attributes: [:images, :videos])
```

**Comment by novill** [comment]
I've tried today and got empty result.

**Comment by gottfrois** [comment]
Looked a bit at this and it would require some major changes to make this possible. There are unfortunately no easy work around :-/
