### ISSUE TITLE
json 1.8.6 is too old

### ISSUE THREAD

**Issue by chianhsieh** [gottfrois/link_thumbnailer#115]
Hello,

link_thumbnailer use Gem json 1.8.6 as well, but the newest version is 2.0.2.
It might have dependency conflict with our existing system.

If I want to upgrade json to 2.0.2, what should I do?
Thank you.

**Comment by gottfrois** [comment]
You can fork the repo and try to upgrade on your side, see if everything works as expected. If it's the case, you can submit a pull request :)

**Comment by gottfrois** [comment]
Upgraded
