### ISSUE TITLE
Not generating correct image src 

### ISSUE THREAD

**Issue by naiyyar** [gottfrois/link_thumbnailer#123]
When trying to generate images for this url http://etiquettable.eco2initiative.com/
It's Not giving correct image src. not event showing image thumbnail.
 I checked here too http://link-thumbnailer-demo.herokuapp.com/ 

Thanks

**Comment by gottfrois** [comment]
Seems to work now with `v3.4.0`:

```ruby
2.6.6 :007 > r = LinkThumbnailer.generate('http://etiquettable.eco2initiative.com/');nil
r.images.first.s => nil
2.6.6 :008 > r.images.first.src
 => "https://etiquettable.eco2initiative.com/wp-content/uploads/2017/01/Etiquettable_mockup-iphone-01web.jpg"
2.6.6 :009 > r.images.first.size
 => [2000, 1250]
```
