### ISSUE TITLE
Ruby crash when trying to parse certain sites

### ISSUE THREAD

**Issue by mskubenich** [gottfrois/link_thumbnailer#128]
Hi ! 

Thank you for your amazing job !

I encountered a strange crash in ruby after trying next line:

`LinkThumbnailer.generate('http://nsdateformatter.com/')`

Here is what i see in terminal: 

`
ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin17]

-- Crash Report log information --------------------------------------------
   See Crash Report log file under the one of following:                    
     * ~/Library/Logs/CrashReporter                                         
     * /Library/Logs/CrashReporter                                          
     * ~/Library/Logs/DiagnosticReports                                     
     * /Library/Logs/DiagnosticReports                                      
   for more details.                                                        
Don't forget to include the above Crash Report log file in bug reports.     

-- Control frame information -----------------------------------------------
c:0059 p:---- s:0292 e:000291 CFUNC  :encode!
c:0058 p:0043 s:0286 e:000285 METHOD /Users/michaelskubenych/dev/link_thumbnailer/lib/link_thumbnailer/model.rb:16
c:0057 p:0023 s:0281 e:000280 METHOD /Users/michaelskubenych/dev/link_thumbnailer/lib/link_thumbnailer/models/description.rb:15 [FINISH]
c:0056 p:---- s:0273 e:000272 CFUNC  :new
c:0055 p:0027 s:0265 e:000264 METHOD /Users/michaelskubenych/dev/link_thumbnailer/lib/link_thumbnailer/scrapers/default/description.rb:43
c:0054 p:0017 s:0258 e:000257 BLOCK  /Users/michaelskubenych/dev/link_thumbnailer/lib/link_thumbnailer/scrapers/default/description.rb:23 [FINISH]
c:0053 p:---- s:0253 e:000252 IFUNC 
c:0052 p:---- s:0250 e:000249 IFUNC 
c:0051 p:---- s:0247 e:000246 CFUNC  :each
c:0050 p:---- s:0244 e:000243 CFUNC  :each_with_index
c:0049 p:---- s:0241 e:000240 CFUNC  :each
c:0048 p:---- s:0238 e:000237 CFUNC  :map
c:0047 p:0015 s:0234 e:000233 METHOD /Users/michaelskubenych/dev/link_thumbnailer/lib/link_thumbnailer/scrapers/default/description.rb:23
c:0046 p:0028 s:0230 e:000229 METHOD /Users/michaelskubenych/dev/link_thumbnailer/lib/link_thumbnailer/scrapers/default/description.rb:12
c:0045 p:0061 s:0226 e:000223 METHOD /Users/michaelskubenych/dev/link_thumbnailer/lib/link_thumbnailer/scrapers/base.rb:29
c:0044 p:0031 s:0219 e:000218 BLOCK  /Users/michaelskubenych/dev/link_thumbnailer/lib/link_thumbnailer/scraper.rb:39 [FINISH]
c:0043 p:---- s:0215 e:000214 CFUNC  :each
c:0042 p:0015 s:0211 e:000210 BLOCK  /Users/michaelskubenych/dev/link_thumbnailer/lib/link_thumbnailer/scraper.rb:38 [FINISH]
c:0041 p:---- s:0207 e:000206 CFUNC  :each
`
something about 1000 lines of error backtrace

Looks like the problem is related to this one [https://bugs.ruby-lang.org/issues/13339](https://bugs.ruby-lang.org/issues/13339). And this is known issue.

So i don't know how to fix it. But maybe the temporary solution would be just to not crash system)

[https://github.com/gottfrois/link_thumbnailer/pull/127](https://github.com/gottfrois/link_thumbnailer/pull/127)

Thanks.

**Comment by gottfrois** [comment]
Can you try with latest ruby version?

**Comment by mskubenich** [comment]
I tried with 2.4.0 and 2.4.1

**Comment by gottfrois** [comment]
Merged your fix
