### ISSUE TITLE
Image stats broken for gif images

### ISSUE THREAD

**Issue by mbajur** [gottfrois/link_thumbnailer#132]
I recently noticed that link_thumbnailer is not able to fetch metadata for gif images (when using `config.image_stats = true`). After doing a tiny research it turned out it's a `image_info` fault but i doubt we can do much about it as it's not maintained since 2015.

You can test the behavior on these links:
- https://umaar.com/dev-tips/151-screenshot-capture/
- https://www.producthunt.com/posts/irl-glasses-1

Running LinkThumbnailer on these with `image_stats` enabled takes a lot of time and results in nils for dimensions and mime type. On the other hand, `fast_image` deals perfectly fine with these.

**Comment by mbajur** [comment]
Update:
It turned out image_info actually do have a gif support (https://github.com/gottfrois/image_info/search?q=gif&unscoped_q=gif) but it seems it's broken anyway.

Also - it's broken for other kinds of images, scrapping `https://umaar.com/dev-tips/151-screenshot-capture/` gives us two images in the results (gif and png) and both of them have dimensions set to nil as well as format.

**Comment by gottfrois** [comment]
Hey @mbajur thanks for the notice! Yes I own `image_info` and it was based on `fast_image` so it should definitely work the same way 😡 !
I'm quite busy at the moment but I'll gladly accept PRs if you're willing to have a look.

**Comment by gottfrois** [comment]
@mbajur I've released a new version of [ImageInfo](https://github.com/gottfrois/image_info/releases/tag/v1.2.0) which fixes the issues with GIF files. I'm going to make a release of LinkThumnailer as well.
