### ISSUE TITLE
undefined method `src' for nil:NilClass 

### ISSUE THREAD

**Issue by lesrima88** [gottfrois/link_thumbnailer#136]
This happens randomly, sometimes it loads up the website image without any issues but 50% of the time i get 'undefined method `src' for nil:NilClass' error.  What could be the problem?

<%= image_tag LinkThumbnailer.generate(post.url).images.first.src.to_s %>

**Comment by maia** [comment]
Most likely LinkThumbnailer.generate(post.url).images returns an empty array as no images are found, therefor #first returns nil.

**Comment by gottfrois** [comment]
@lesrima88 you should probably check if LinkThumbnailer was able to retrieve some images with something like:

```ruby
image = LinkThumbnailer.generate(post.url).images.first
if image
...
end
```
