### ISSUE TITLE
warning: no framework detected.

### ISSUE THREAD

**Issue by eddietejeda** [gottfrois/link_thumbnailer#144]
Great library. I use it in a Sinatra app, but I always see this error message when it boots:

https://github.com/gottfrois/link_thumbnailer/blob/master/lib/link_thumbnailer.rb#L30

Is this message necessary? Especially since the documentation says "Works with and without Rails."

**Comment by gottfrois** [comment]
Thanks @eddietejeda for bringing this up.
I think you are right, this is not very useful and I could actually remove all the rails related parts since the gem doesn't really hook with rails in anyway.

**Comment by gottfrois** [comment]
I've removed the code related to rails. It will be gone in the next release 👍
