### ISSUE TITLE
403 "Forbidden" (LinkThumbnailer::HTTPError)

### ISSUE THREAD

**Issue by mitesh-kumar** [gottfrois/link_thumbnailer#145]
I am getting error with Https://app.asana.com/0/11996253
69654937/list as 403 "Forbidden" (LinkThumbnailer::HTTPError). Can anyone resolved this or I am missing something . I am using ruby 2.6.1.

**Comment by gottfrois** [comment]
403 means this page is protected behind user credentials. You'll need to provide credentials, most likely with an HTTP Authorization header.
