### ISSUE TITLE
Blocked by CORs policy

### ISSUE THREAD

**Issue by corejh** [gottfrois/link_thumbnailer#146]
Hey there, does this gem work anymore? On the example http://link-thumbnailer-demo.herokuapp.com/ the application throws CORs errors whenever I try on chrome or firefox. 

If this gem isn't supported anymore, does anybody have any alternatives?

**Comment by gottfrois** [comment]
Hey @corejh, this is because you are on the non https version of the website and the script tries to send a request on with https which triggers the CORS error.

Head to https://link-thumbnailer-demo.herokuapp.com/ and it works fine.
