### ISSUE TITLE
Freezing for certain urls

### ISSUE THREAD

**Issue by johansenja** [gottfrois/link_thumbnailer#150]
I have two urls where this is currently the case:
`https://www.gov.uk/government/organisations/department-of-health`
and
`https://www.gov.uk/ccs`

and I encounter it just with `LinkThumbnailer.generate(url)`.

If I do this in irb then interrupt the process, I can trace it back to https://github.com/ruby/ruby/blob/d53493715cd1a1463b98291e0ad92e2723236698/ext/openssl/lib/openssl/buffering.rb#L81, where it seems to be encountering EAGAIN and is probably stuck in `retry` loop. But I have no idea why this might be the case here in particular; does anyone have any suggestions?

Ruby version 2.7.1
Gem version 3.4.0

**Comment by gottfrois** [comment]
Seems to be working fine on my environment, might be related to how openssl is installed on your env.
