### ISSUE TITLE
No title or image returned for google.co.uk

### ISSUE THREAD

**Issue by jeremygoh** [gottfrois/link_thumbnailer#19]
Initially Linkthumbnailer.generate for http://google.co.uk and all other google domains was returning nil.

After setting strict to false in link_thumbnailer.rb, we are now getting an object. However, this object only contains the URL and not the title or any images.

This doesn't seem to be an issue with any other URL.

**Comment by jayaprakash88** [comment]
i am try to get google image and description but i am getting error 
LinkThumbnailer.generate('http://google.co.in', :strict=> false)
Error is
NoMethodError: undefined method `strict=' for #<LinkThumbnailer::Configuration:0x0000000d6f8ff8>

Please give me a solution

**Comment by gottfrois** [comment]
@jayaprakash88 the `strict` option does not exist in latest version of the gem:

```
LinkThumbnailer.generate('http://google.co.in')
 => #<LinkThumbnailer::Models::Website:0x007fba4c9d16c0 @images=[], @videos=[], @url=#<URI::HTTP http://www.google.co.in/>, @title="Google", @description="© 2017 - Privacy - Terms", @favicon="/images/branding/product/ico/googleg_lodp.ico">
```

**Comment by jayaprakash88** [comment]
Yes i am getting response but i haven't  get default google images and description. In demo url (http://link-thumbnailer-demo.herokuapp.com/) i am getting image and description as well ..

**Comment by gottfrois** [comment]
the demo does not return any images as well http://d.pr/i/CHwc
Correct me if i'm wrong but `http://google.co.in` does not have any image on the page
