### ISSUE TITLE
Demo app broken: POST http://link-thumbnailer-demo.herokuapp.com/link/preview 500 (Internal Server Error) 

### ISSUE THREAD

**Issue by lolmaus** [gottfrois/link_thumbnailer#33]

**Comment by avandrel** [comment]
I have similar issue for polish site: 'http://wroclaw.wyborcza.pl/wroclaw/1,35771,19481129,razem-krytykuje-esk-i-chce-audytu-finansowego-i-artystycznego.html' - it's example article from Polish newspaper's site.
It's not working on demo page, I got 'NetworkError: 400 Bad Request - http://link-thumbnailer-api.herokuapp.com/thumbnails/new?callback=angular.callbacks._1&url=http:%2F%2Fwroclaw.wyborcza.pl%2Fwroclaw%2F1,35771,19481129,razem-krytykuje-esk-i-chce-audytu-finansowego-i-artystycznego.html'.
It's working without exeption when I test it from irb. But here comes another issue with that page (as whole) - link_thumbnailer is recognized as client with Adblock/uBlock enabled and some meta data is hidden (like description or title). Should I create another issue for that behaviour?

**Comment by gottfrois** [comment]
Yes please create a separate issue for the adblock thing. Can you elaborate a bit more about the adblock issue there too please?

Thanks !
