### ISSUE TITLE
Not detecting an image even if the url has a declared og:image

### ISSUE THREAD

**Issue by kurtish** [gottfrois/link_thumbnailer#47]
Hi,

If you try to use the thumbnailer on a site such as http://www.nytimes.com/2014/11/16/technology/esports-call-of-duty-nadeshot-celebrity-success.html you well see that it does not detect any image. 

 If you view the source code on the link above you will see that it does have an og:image tag that does point to a working image:

meta property="og:image" content="http://static01.nyt.com/images/2014/11/13/multimedia/gamer-nadeshot/gamer-nadeshot-videoSixteenByNine1050.jpg"

Hopefully this is an example you can use to fix this issue.

Kurtis

**Comment by gottfrois** [comment]
Closing the issue since the dom is changed using javascript
