### ISSUE TITLE
ArgumentError (invalid byte sequence in UTF-8) parsing google.com

### ISSUE THREAD

**Issue by sangregoriopaolo** [gottfrois/link_thumbnailer#50]
Hi,

If I run the following line, from my 'rails c'
    
    object = LinkThumbnailer.generate('http://google.com')

I get the following stack trace:
    
    ArgumentError: invalid byte sequence in UTF-8
    	from /Users/paolo/.rvm/gems/ruby-2.2.0@stuff/gems/link_thumbnailer-2.3.2/lib/link_thumbnailer/model.rb:12:in `gsub'
    	from /Users/paolo/.rvm/gems/ruby-2.2.0@stuff/gems/link_thumbnailer-2.3.2/lib/link_thumbnailer/model.rb:12:in `sanitize'
    	from /Users/paolo/.rvm/gems/ruby-2.2.0@stuff/gems/link_thumbnailer-2.3.2/lib/link_thumbnailer/models/description.rb:13:in `initialize'
    	from /Users/paolo/.rvm/gems/ruby-2.2.0@stuff/gems/link_thumbnailer-2.3.2/lib/link_thumbnailer/scrapers/default/description.rb:41:in `new'
    	from /Users/paolo/.rvm/gems/ruby-2.2.0@stuff/gems/link_thumbnailer-2.3.2/lib/link_thumbnailer/scrapers/default/description.rb:41:in `modelize'
    	from /Users/paolo/.rvm/gems/ruby-2.2.0@stuff/gems/link_thumbnailer-2.3.2/lib/link_thumbnailer/scrapers/default/description.rb:21:in `block in model_from_body'
    	from /Users/paolo/.rvm/gems/ruby-2.2.0@stuff/gems/link_thumbnailer-2.3.2/lib/link_thumbnailer/scrapers/default/description.rb:21:in `each'
    	from /Users/paolo/.rvm/gems/ruby-2.2.0@stuff/gems/link_thumbnailer-2.3.2/lib/link_thumbnailer/scrapers/default/description.rb:21:in `each_with_index'
    	from /Users/paolo/.rvm/gems/ruby-2.2.0@stuff/gems/link_thumbnailer-2.3.2/lib/link_thumbnailer/scrapers/default/description.rb:21:in `each'
    	from /Users/paolo/.rvm/gems/ruby-2.2.0@stuff/gems/link_thumbnailer-2.3.2/lib/link_thumbnailer/scrapers/default/description.rb:21:in `map'
    	from /Users/paolo/.rvm/gems/ruby-2.2.0@stuff/gems/link_thumbnailer-2.3.2/lib/link_thumbnailer/scrapers/default/description.rb:21:in `model_from_body'
    	from /Users/paolo/.rvm/gems/ruby-2.2.0@stuff/gems/link_thumbnailer-2.3.2/lib/link_thumbnailer/scrapers/default/description.rb:10:in `value'
    	from /Users/paolo/.rvm/gems/ruby-2.2.0@stuff/gems/link_thumbnailer-2.3.2/lib/link_thumbnailer/scrapers/base.rb:25:in `call'
    	from /Users/paolo/.rvm/gems/ruby-2.2.0@stuff/gems/link_thumbnailer-2.3.2/lib/link_thumbnailer/scraper.rb:37:in `block (2 levels) in call'
    	from /Users/paolo/.rvm/gems/ruby-2.2.0@stuff/gems/link_thumbnailer-2.3.2/lib/link_thumbnailer/scraper.rb:36:in `each'
    	from /Users/paolo/.rvm/gems/ruby-2.2.0@stuff/gems/link_thumbnailer-2.3.2/lib/link_thumbnailer/scraper.rb:36:in `block in call'
    	from /Users/paolo/.rvm/gems/ruby-2.2.0@stuff/gems/link_thumbnailer-2.3.2/lib/link_thumbnailer/scraper.rb:35:in `each'
    	from /Users/paolo/.rvm/gems/ruby-2.2.0@stuff/gems/link_thumbnailer-2.3.2/lib/link_thumbnailer/scraper.rb:35:in `call'
    	from /Users/paolo/.rvm/gems/ruby-2.2.0@stuff/gems/link_thumbnailer-2.3.2/lib/link_thumbnailer/page.rb:18:in `generate'
    	from /Users/paolo/.rvm/gems/ruby-2.2.0@stuff/gems/link_thumbnailer-2.3.2/lib/link_thumbnailer.rb:16:in `generate'
    	from (irb):1
    	from /Users/paolo/.rvm/gems/ruby-2.2.0@stuff/gems/railties-4.2.0/lib/rails/commands/console.rb:110:in `start'
    	from /Users/paolo/.rvm/gems/ruby-2.2.0@stuff/gems/railties-4.2.0/lib/rails/commands/console.rb:9:in `start'
    	from /Users/paolo/.rvm/gems/ruby-2.2.0@stuff/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:68:in `console'
    	from /Users/paolo/.rvm/gems/ruby-2.2.0@stuff/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
    	from /Users/paolo/.rvm/gems/ruby-2.2.0@stuff/gems/railties-4.2.0/lib/rails/commands.rb:17:in `<top (required)>'
    	from bin/rails:4:in `require'
    	from bin/rails:4:in `<main>'

Does it happen to anyone else? Trying to parse stackoverflow.com works well instead.

Thanks!

**Comment by gottfrois** [comment]
Hum, seems to work fine for me:

```ruby
object = LinkThumbnailer.generate('http://google.com')
 => #<LinkThumbnailer::Models::Website:0x007ff58111b628 @images=[http://www.google.fr/images/icons/product/chrome-48.png], @videos=[], @url=#<URI::HTTP:0x007ff581375f90 URL:http://www.google.fr/?gfe_rd=cr&ei=dMa7VPO5N4mx8weRi4CICQ>, @title="Google", @description="© 2015 - Confidentialité - Conditions", @favicon="">
```

Try forking the gem and add this code to the top of this file `lib/link_thumbnailer/model.rb`

```ruby
# encoding: utf-8
```

**Comment by sangregoriopaolo** [comment]
Just tried, same error :(
My ruby version is

    ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin14]

And my rails version

    Rails 4.2.0

Thanks for your support!

**Comment by gottfrois** [comment]
can you try with a lower ruby version ? I just tried with `ruby-2.0.0-p481` and `ruby-1.9.3-p551`. Rails version should not be an issue since the gem can work without it.

**Comment by sangregoriopaolo** [comment]
Looks like I get the same error even with ruby 2.0 :(

    2.0.0p353 :001 > object = LinkThumbnailer.generate('http://google.com')
    ArgumentError: invalid byte sequence in UTF-8
    	from /Users/paolo/.rvm/gems/ruby-2.0.0-p353/bundler/gems/link_thumbnailer-24d1a7dd56ef/lib/link_thumbnailer/model.rb:13:in `gsub'
    	from /Users/paolo/.rvm/gems/ruby-2.0.0-p353/bundler/gems/link_thumbnailer-24d1a7dd56ef/lib/link_thumbnailer/model.rb:13:in `sanitize'
    	from /Users/paolo/.rvm/gems/ruby-2.0.0-p353/bundler/gems/link_thumbnailer-24d1a7dd56ef/lib/link_thumbnailer/models/description.rb:13:in `initialize'
    	from /Users/paolo/.rvm/gems/ruby-2.0.0-p353/bundler/gems/link_thumbnailer-24d1a7dd56ef/lib/link_thumbnailer/scrapers/default/description.rb:41:in `new'
    	from /Users/paolo/.rvm/gems/ruby-2.0.0-p353/bundler/gems/link_thumbnailer-24d1a7dd56ef/lib/link_thumbnailer/scrapers/default/description.rb:41:in `modelize'
    	from /Users/paolo/.rvm/gems/ruby-2.0.0-p353/bundler/gems/link_thumbnailer-24d1a7dd56ef/lib/link_thumbnailer/scrapers/default/description.rb:21:in `block in model_from_body'
    	from /Users/paolo/.rvm/gems/ruby-2.0.0-p353/bundler/gems/link_thumbnailer-24d1a7dd56ef/lib/link_thumbnailer/scrapers/default/description.rb:21:in `each'
    	from /Users/paolo/.rvm/gems/ruby-2.0.0-p353/bundler/gems/link_thumbnailer-24d1a7dd56ef/lib/link_thumbnailer/scrapers/default/description.rb:21:in `each_with_index'
    	from /Users/paolo/.rvm/gems/ruby-2.0.0-p353/bundler/gems/link_thumbnailer-24d1a7dd56ef/lib/link_thumbnailer/scrapers/default/description.rb:21:in `each'
    	from /Users/paolo/.rvm/gems/ruby-2.0.0-p353/bundler/gems/link_thumbnailer-24d1a7dd56ef/lib/link_thumbnailer/scrapers/default/description.rb:21:in `map'
    	from /Users/paolo/.rvm/gems/ruby-2.0.0-p353/bundler/gems/link_thumbnailer-24d1a7dd56ef/lib/link_thumbnailer/scrapers/default/description.rb:21:in `model_from_body'
    	from /Users/paolo/.rvm/gems/ruby-2.0.0-p353/bundler/gems/link_thumbnailer-24d1a7dd56ef/lib/link_thumbnailer/scrapers/default/description.rb:10:in `value'
    	from /Users/paolo/.rvm/gems/ruby-2.0.0-p353/bundler/gems/link_thumbnailer-24d1a7dd56ef/lib/link_thumbnailer/scrapers/base.rb:25:in `call'
    	from /Users/paolo/.rvm/gems/ruby-2.0.0-p353/bundler/gems/link_thumbnailer-24d1a7dd56ef/lib/link_thumbnailer/scraper.rb:37:in `block (2 levels) in call'
    	from /Users/paolo/.rvm/gems/ruby-2.0.0-p353/bundler/gems/link_thumbnailer-24d1a7dd56ef/lib/link_thumbnailer/scraper.rb:36:in `each'
    	from /Users/paolo/.rvm/gems/ruby-2.0.0-p353/bundler/gems/link_thumbnailer-24d1a7dd56ef/lib/link_thumbnailer/scraper.rb:36:in `block in call'
    	from /Users/paolo/.rvm/gems/ruby-2.0.0-p353/bundler/gems/link_thumbnailer-24d1a7dd56ef/lib/link_thumbnailer/scraper.rb:35:in `each'
    	from /Users/paolo/.rvm/gems/ruby-2.0.0-p353/bundler/gems/link_thumbnailer-24d1a7dd56ef/lib/link_thumbnailer/scraper.rb:35:in `call'
    	from /Users/paolo/.rvm/gems/ruby-2.0.0-p353/bundler/gems/link_thumbnailer-24d1a7dd56ef/lib/link_thumbnailer/page.rb:18:in `generate'
    	from /Users/paolo/.rvm/gems/ruby-2.0.0-p353/bundler/gems/link_thumbnailer-24d1a7dd56ef/lib/link_thumbnailer.rb:16:in `generate'
    	from (irb):1
    	from /Users/paolo/.rvm/gems/ruby-2.0.0-p353/gems/railties-4.2.0/lib/rails/commands/console.rb:110:in `start'
    	from /Users/paolo/.rvm/gems/ruby-2.0.0-p353/gems/railties-4.2.0/lib/rails/commands/console.rb:9:in `start'
    	from /Users/paolo/.rvm/gems/ruby-2.0.0-p353/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:68:in `console'
    	from /Users/paolo/.rvm/gems/ruby-2.0.0-p353/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
    	from /Users/paolo/.rvm/gems/ruby-2.0.0-p353/gems/railties-4.2.0/lib/rails/commands.rb:17:in `<top (required)>'
    	from bin/rails:4:in `require'
    	from bin/rails:4:in `<main>'2.0.0p353

**Comment by gottfrois** [comment]
Can you try to replace the following code in your fork:

```ruby
def sanitize(str)
  return unless str
  str.strip.gsub(/[\r\n\f]+/, "\n")
end
```

by this one:

```ruby
def sanitize(str)
  return unless str
  str.strip.encode('UTF-8', 'binary', invalid: :replace, undef: :replace, replace: '').gsub(/[\r\n\f]+/, "\n")
end
```

in the following file https://github.com/gottfrois/link_thumbnailer/blob/master/lib/link_thumbnailer/model.rb#L10-L13

**Comment by sangregoriopaolo** [comment]
Hi! Great, it works :) so basically you are replacing bad stuff with spaces. Great!
Do you want a pull request?

**Comment by gottfrois** [comment]
not with spaces, but with empty string. Do not bother, I was planning on updating some code, i'll do the update and check couple more things :)

**Comment by sangregoriopaolo** [comment]
Ok thanks for the support! :)

**Comment by ckolderup** [comment]
Hi,

Looks like this fix hasn't landed in a released gem version yet. Any chance it'll be there soon?

**Comment by gottfrois** [comment]
Oh sorry about that guys, I simply forgot... Your code sounds good, feel free to open a PR and i'll merge it into master as well as bumping the gem version.
