### ISSUE TITLE
Youtube videos do not generate videos

### ISSUE THREAD

**Issue by kikito** [gottfrois/link_thumbnailer#51]
Hi there,

Youtube does not seem to be generating videos for LinkThumbnailer:

    LinkThumbnailer.generate('https://www.youtube.com/watch?v=PqkR0SwFN_4')
    => #<LinkThumbnailer::Models::Website:0x00000105050428
     @images=[#<LinkThumbnailer::Models::Image:0x0000010507b060 @size=[480, 360], @src="https://i.ytimg.com/vi/PqkR0SwFN_4/hqdefault.jpg", @type=:jpeg>],
     @title="Marvel's Avengers: Age of Ultron extended trailer UK - OFFICIAL | HD",
     @url=#<URI::HTTPS:0x0000010948fcd8 URL:https://www.youtube.com/watch?v=PqkR0SwFN_4>,
     @videos=[]>

Is there something I can do to fix this?

**Comment by gottfrois** [comment]
Hey, yep it seems broken. I will look at it and make a patch.

**Comment by gottfrois** [comment]
Fixed in `v2.5.0`
