### ISSUE TITLE
fetch method causing my app to break

### ISSUE THREAD

**Issue by fainashalts** [gottfrois/link_thumbnailer#52]
Hi there,

LinkThumbnailer is so great! I've been using it in my app, and the problem I'm having is that for some websites when fetch can't get the site in question, it breaks my whole app. I've been testing it with sites I know won't work because I'm trying to rescue the error or otherwise cause all the links that DO work to show up on the page when a bad link has been added.

My view for the links index looks like this, in relevant part:
<% @links.order(:cached_votes_total => :desc).each do  |link| %>

          <ul class="list-unstyled">
            <li><h4><a href="<%= link.url %>"><%= fetch(link.url.to_s).title %></h4></li>
            <li><%= fetch(link.url.to_s).description %></li>      
            <li><img class="link-img" src="<%= fetch(link.url.to_s).images.first.src%>"></li>
            <li><%= link_to link.try(:subtopic).try(:name), subtopic_path(link.subtopic) %></li>
            

I tried to rescue bad urls in my controller, but it doesn't always work:
 
def create
		begin
			@link = current_user.links.new(link_params)
		
		rescue
			@object = LinkThumbnailer.generate(@link.url, verify_ssl: true)
		
		rescue Exception
			redirect_to :back
			# render :text => "Sorry, that link is invalid! Please hit your browser's back button to return to Party On Code and try again!"
			puts "This link is invalid. Please try again!"
		else

			@link.save
					redirect_to :back
		end
	
	end

When a link that is bad gets saved, I get the following error: 
SocketsError in Links#Index
getaddrinfo: nodename nor servname provided, or not known

And I have to go in to my rails console to delete the offending link manually before all the others show up.

Is there something I can do with fetch to resolve this issue, or perhaps there is something simple I am missing? 

I'm sorry if this question is not in the right format or if I haven't provided enough information, I'm new to coding and this is the first issue I've posted on a gem. Please let me know if there is anything I can do to clarify, and thank you!

**Comment by gottfrois** [comment]
Hey there,

So i am not sure to fully understand what you are trying to do. What's is `fetch`? and where is it coming from?

Now, there is something wrong with the code sample. I would not put 2 rescue following each other but do something like this instead:

```ruby
  def create
    @link = current_user.links.new(link_params)

    if thumbnail
      # url is valid, do something with the thumbnail
      @link.save
    else
      # oops, something went wrong with this url, thumbnail is nil. You should handle the error
    end

    redirect_to :back
  end

  private

  def thumbnail
    @thumbnail ||= LinkThumbnailer.generate(@link.url, verify_ssl: true)
  rescue LinkThumbnailer::Exceptions
    nil
  end
```

```
def some_code
end
```

Also, not sure the above code would catch the exception you mentioned (SocketsError in Links#Index
getaddrinfo: nodename nor servname provided, or not known) so could you give me an url that cause this issue so I can have a better idea of what's going on?

Finally, to share good code samples, put your code between "```" (3 backquotes) like this http://d.pr/i/RDV

**Comment by fainashalts** [comment]
Hi, 

My apologies, I think I left out a crucial bit. Fetch is the method I'm using to generate a new thumbnail: 

```
module LinksHelper

  def fetch(url)
    LinkThumbnailer.generate(url)   
  end

end
```

One link this has happened with is http://www.wonwork.co, which I know isn't an existing webpage. I have also tried it with my portfolio website, which isn't set up for opengraph, and the same thing happens: fainashalts.com.  It seems like sometimes my rescue block catches it, and sometimes it doesn't. I am trying to use the rescue block to keep the link from saving if it is bad.  If the bad link saves, I'm unable to load my index of links and get the error mentioned.

**Comment by gottfrois** [comment]
Ok, couple things to note here:

As you mentioned http://www.wonwork.co does not resolve, that's why you are seeing that `SocketError` exception. Since `SocketError` is a subclass of `StandardError`, you can rescue using `LinkThumbnailer::Exception` class:

```ruby
def thumbnail
  @thumbnail ||= LinkThumbnailer.generate(@link.url, verify_ssl: true)
rescue LinkThumbnailer::Exceptions
  # SocketError will be catched and nil will be returned
  nil
end
```

Secondly, your personal blog url does not work because it's actually not a valid url, here is an example in irb console:

```ruby
> LinkThumbnailer.generate('fainashalts.com')
LinkThumbnailer::BadUriFormat: LinkThumbnailer::BadUriFormat
```

and now:

```ruby
> LinkThumbnailer.generate('http://fainashalts.com')
 => #<LinkThumbnailer::Models::Website:0x007fd892537c40 @images=[], @videos=[], @url=#<URI::HTTP:0x007fd892527980 URL:http://fainashalts.com>, @title="fainashalts", @description=nil, @favicon="">
```

So you'll want to make sure you pass valid urls, that begins with `http://` or `https://`. Note that `LinkThumbnailer::BadUriFormat` is an exception that will be rescued with the code sample I have you, so you would receive `nil` instead of raising the exception.

Hope it helps.

**Comment by gottfrois** [comment]
I would suggest to build an abstract class around LinkThumbnailer. This way you could deal more easily with the exceptions:

```ruby
class Thumbnail

  attr_reader :url

  def initialize(url)
    @url = url
  end

  def title
    thumbnailer.try(:title)
  end

  def description
    thumbnailer.try(:description)
  end

  private

  def thumbnailer
    @thumbnailer ||= LinkThumbnailer.generate(url, verify_ssl: false)
  rescue LinkThumbnailer::Exceptions
    nil
  end
  
end
```

Then in irb console:

```ruby
> t = Thumbnail.new('http://github.com')
 => #<Thumbnail:0x007f953c536c80 @url="http://github.com">
> t.title
 => "Build software better, together"
> t.description
 => "GitHub is the best place to build software together. Over 4 million people use GitHub to share code."
> t = Thumbnail.new('fainashalts.com')
 => #<Thumbnail:0x007f953c1b3310 @url="fainashalts.com">
> t.title
 => nil
> t.description
 => nil
```

**Comment by gottfrois** [comment]
Closing, feel free to re-open if you have more questions
