### ISSUE TITLE
Redirect limit error

### ISSUE THREAD

**Issue by aitharaju** [gottfrois/link_thumbnailer#55]
The following url throws the redirect limit error - http://www.nytimes.com/2015/03/25/opinion/schools-need-albanys-help-now.html. I tried increasing the redirect limit and it didn't help. Any ideas on how to fix this issue?

**Comment by 0mega** [comment]
I've the same issue with most of the NYT articles. Haven't had time to look into what's exactly happening there.

**Comment by aitharaju** [comment]
I think it needs a cookie to respond back, if you try to make a request in the browser, it redirects you to a login page which sets the browser cookie and uses the cookie to retrieve the page.

**Comment by gottfrois** [comment]
Fixed on `v2.5.1`. Sorry for the delay :)
