### ISSUE TITLE
Rendering a link gives "OpenURI::HTTPError: 410 Gone".

### ISSUE THREAD

**Issue by deepak07** [gottfrois/link_thumbnailer#60]
This happened since the gem version bumped from '*2.4.0*' to '*2.5.1*'. 
I tried render a link [https://www.youtube.com/watch?v=rSQNi5sAwuc](https://www.youtube.com/watch?v=rSQNi5sAwuc). It raised an **OpenURI::HTTPError: 410 Gone** error.
 
object = LinkThumbnailer.generate('https://www.youtube.com/watch?v=rSQNi5sAwuc')

**NOTE: This was working  fine in '*2.4.0*'**

**Comment by gottfrois** [comment]
It's actually not related to the gem. In order to fetch video metadata, there is a HTTP call done on youtube API that look like this:

```
curl -i http://gdata.youtube.com/feeds/api/videos/rSQNi5sAwuc\?v\=2\&alt\=json
```

Unfortunately the response is now a `HTTP/1.1 410 Gone`

I'll push an update in order to avoid the exception and simply not set video metadata

**Comment by deepak07** [comment]
There has been some update in the **'video_info'** gem that is being used for rendering youtube metadata. Now for fetching youtube data, we need to specify API Keys in our application.
But the changes are only available in the *master* branch. After a stable release is made for **'video_info'**, I think it will be possible to make a configuration for setting VideoInfo Youtube API keys using the LinkThumbnailer config.

For now I have included:

*gem 'video_info', github: 'thibaudgg/video_info'*

in my Gemfile and setting the *VideoInfo.provider_api_keys* in my project initializer file.
This has solved the problem for now and the video paths are rendered.

**Comment by gottfrois** [comment]
yes, i'm waiting for their code to be more stable :) Glad it works for you

**Comment by deepak07** [comment]
I think the issue with video_info gem has been solved. Could you update the gem with the new changes.

**Comment by sudiptam123** [comment]
Hi, recently i am getting issue for LinkThumbnailer unable to generate vimeo url throwing error (VideoInfo::HttpError: unexpected network error while fetching information about the video).
All other vimeo url's gets created successfully only problem is with specific vimeo url's.
Code :-
obj = LinkThumbnailer.generate("https://vimeo.com/309953801/b27d2ce475")

Error :-
VideoInfo::HttpError: unexpected network error while fetching information about the video

Below is the url attached :-
https://vimeo.com/309953801/b27d2ce475

Gems used are as follows -:
gem 'video_info', '2.6.0'
gem 'link_thumbnailer'

**Comment by gottfrois** [comment]
The error seems to indicate an issue parsing video metadata using the video_info gem https://github.com/thibaudgg/video_info

LinkThumbnailer uses this gem under the hood to get metadata about the video.
Can you check on their github about an opened issue maybe?
