### ISSUE TITLE
having the http response header in return

### ISSUE THREAD

**Issue by chuenlok** [gottfrois/link_thumbnailer#61]
If a link to pdf is used, the description will be some unreadable texts. It would be great if the contetn-type can be checked before using the description or other things returned from link_thumbnailer.

For example,
http://prawnpdf.org/manual.pdf
will return 

> %PDF-1.4 % 1 0 obj /Producer >> endobj 2 0 obj > endobj 3 0 obj > endobj 4 0 obj > stream q endstream endobj 5 0 obj > >> endobj 6 0 obj > stream q q 126.9 0.0 0.0 127.8 46.0 572.2 cm /I1 Do Q BT 206 578.2 Td /F2.0 100 Tf [ 15 ] TJ ET BT 206 502.26 Td /F3.0 60 Tf [] TJ ET BT 426 71.384 Td /F1.0 12 Tf [] TJ ET BT 426 57.512 Td /F1.0 12 Tf [ 10 20 80 ] TJ ET BT 426 43.64 Td /F1.0 12 Tf [] TJ ET Q endstream endobj 7 0 obj > /Font > >> >> endobj 8 0 obj >] >> stream x}ipXsa$NR$P^--S-IjqcWAiW E[LU: CXse7JTJ,o$ sa~{1@pR5I#KC za)Tavh@[c7LAHQuZnS/MGI(b(!->};P0V*b~(:_J S D V.pk +zLaTAi;]QxbNV2#^Y+o(R`xaOXT^]QiW ]@-p h534 bzec] \|(ChO??4E'1~+2!)P %Q';X lwkt=0xx]

**Comment by gottfrois** [comment]
yeah, the purpose of them gem is really to scrap html pages, not pdf though. What kind of behavior would you like to see here?

**Comment by gottfrois** [comment]
In version `2.6.0` you can now do:

```ruby
LinkThumbnailer.generate('http://prawnpdf.org/manual.pdf', raise_on_invalid_format: true)
```

Or you can setup permanently in initializer. By default it will not raise.

**Comment by oshields** [comment]
@gottfrois First of all awesome gem! I'm noticing you get a similar crazy description when you pass a url to .jpg or .png.  Is this intentional, the idea being it's the user of the gems responsibility to detect whether the url is already an image file?

**Comment by gottfrois** [comment]
I basically whitelisted processable content types. So if you set the `raise_on_invalid_format` to `false` and still see weird description, can you please have a look at the content-type the server is answering with?

**Comment by oshields** [comment]
Content type would be "Content-Type:image/jpeg"  
Example: http://blog.jimdo.com/wp-content/uploads/2014/01/tree-247122.jpg

The use case is a user enters a url to a jpg, or a gif, in my form, it then gets passed to LinkThumbnailer just like any other url.  LinkThumnailer gracefully returns an object (mostly blank without a title or description) but with the image url.  This way a user of the gem doesn't have to inspect the url himself, determine if its an image, and then not send it to LinkThumbnailer.  No preprocessing required.

**Comment by gottfrois** [comment]
Right, you can control this with the following option:

```ruby
> LinkThumbnailer.generate('http://blog.jimdo.com/wp-content/uploads/2014/01/tree-247122.jpg', raise_on_invalid_format: true)
LinkThumbnailer::FormatNotSupported: image/jpeg
```

and rescue `LinkThumbnailer::FormatNotSupported`
