### ISSUE TITLE
restricting to a-z makes usage for non-english descriptions impossible

### ISSUE THREAD

**Issue by maia** [gottfrois/link_thumbnailer#62]
There seems to be a regex somewhere in the code that removes all characters that aren't a-zA-Z from title/description. This makes using it impossible in languages that have additional letters (which simply can't be deleted from a word). E.g. German has the three umlauts äöü (and their uppercase variants ÄÖÜ) and the letter ß. 

Try this [example link](http://derstandard.at/2000017394465/EZB-Chefoekonom-Unsere-Botschaften-klangen-wie-ein-Mantra), the title contains the word "EZB-Chefökonom" (= EZB chief economist), and link_thumbnailer will return "EZB-Chefkonom" (with missing "ö").

Two possible solutions: allow the entire UTF-8 set or add a regex to the configuration where one can define which letters to keep.

**Comment by gottfrois** [comment]
What version of the gem are you using? In `v2.5.2` it seems to work fine:

```ruby
o.title
 => "EZB-Chefökonom: \"Niedrige Zinsen sind nur kurzfristige Belastung\""
```

**Comment by maia** [comment]
I wasn't using the gem (yet), I tried the demo application at http://link-thumbnailer-demo.herokuapp.com , but it seems it's not running the latest gem version. 
Thanks a lot for fixing the issue!

**Comment by gottfrois** [comment]
Yes I need to upgrade the demo app :)

**Comment by maia** [comment]
I can confirm that the gem does not remove non-ascii. Thanks, not only for handling this issue, but in general - it's an impressive gem you've written.

**Comment by gottfrois** [comment]
Thanks man, always nice to see such comments :)

**Comment by gottfrois** [comment]
Api and demo app is now up to date ;)
