### ISSUE TITLE
should not generate data for pdf, mp3,...

### ISSUE THREAD

**Issue by maia** [gottfrois/link_thumbnailer#64]
LinkThumbnailer tries to generate data for all source urls, no matter what file type they return. I've encountered >500KB long "descriptions" of .pdf and .mp3 files. Could LinkProfiler check which file type is returned and raise an error for everything that's not supported (most likely everything but html)?

**Comment by maia** [comment]
oh, I guess this is a duplicate of #61 , other than the suggestion of having LinkThumbnailer check for the correct file type.

**Comment by gottfrois** [comment]
yes, it's a duplicate, I will look into this :)

**Comment by gottfrois** [comment]
In version `2.6.0` you can now do:

```ruby
LinkThumbnailer.generate('http://prawnpdf.org/manual.pdf', raise_on_invalid_format: true)
```

Or you can setup permanently in initializer. By default it will not raise.

**Comment by maia** [comment]
Thanks a lot! Btw, why are you requiring pry in processor.rb?
