### ISSUE TITLE
Videos: ArgumentError: string contains null byte

### ISSUE THREAD

**Issue by maia** [gottfrois/link_thumbnailer#69]
LinkThumbnailer throws "ArgumentError: string contains null byte“ where querying the same url via VideoInfo causes no problems. See here:

````
url = "https://www.youtube.com/watch?v=Y45Zq-yKpRw“

video = VideoInfo.new(url); video.title
=> "Robert Mitchum - Julian Cope“

lt = LinkThumbnailer.generate(url); lt.title
ArgumentError: string contains null byte
	from …/gems/ruby-2.2.2/gems/oga-1.2.2/lib/oga/xml/lexer.rb:204:in `advance_native'
	from …/gems/ruby-2.2.2/gems/oga-1.2.2/lib/oga/xml/lexer.rb:204:in `block in advance'
	from …/gems/ruby-2.2.2/gems/oga-1.2.2/lib/oga/xml/lexer.rb:147:in `read_data'
	from …/gems/ruby-2.2.2/gems/oga-1.2.2/lib/oga/xml/lexer.rb:203:in `advance'
	from …/gems/ruby-2.2.2/gems/oga-1.2.2/lib/oga/xml/parser.rb:245:in `each_token'
	from …/gems/ruby-2.2.2/gems/oga-1.2.2/lib/oga/xml/parser.rb:282:in `parse'
	from …/gems/ruby-2.2.2/gems/oga-1.2.2/lib/oga/xml/parser.rb:282:in `parse'
	from …/gems/ruby-2.2.2/gems/oga-1.2.2/lib/oga/oga.rb:27:in `parse_html'
	from …/gems/ruby-2.2.2/gems/video_info-2.5.0/lib/video_info/providers/youtube_scraper.rb:91:in `_set_data_from_api'
	from …/gems/ruby-2.2.2/gems/video_info-2.5.0/lib/video_info/provider.rb:32:in `data'
	from …/gems/ruby-2.2.2/gems/video_info-2.5.0/lib/video_info/providers/youtube_scraper.rb:80:in `available?'
	from …/gems/ruby-2.2.2/gems/video_info-2.5.0/lib/video_info/providers/youtube_scraper.rb:68:in `itemprop_node_value'
	from …/gems/ruby-2.2.2/gems/video_info-2.5.0/lib/video_info/providers/youtube_scraper.rb:18:in `duration'
	from …/gems/ruby-2.2.2/gems/link_thumbnailer-3.0.2/lib/link_thumbnailer/video_parser.rb:27:in `duration'
	from …/gems/ruby-2.2.2/gems/link_thumbnailer-3.0.2/lib/link_thumbnailer/models/video.rb:14:in `initialize'
	from …/gems/ruby-2.2.2/gems/link_thumbnailer-3.0.2/lib/link_thumbnailer/scrapers/opengraph/video.rb:29:in `new'
... 29 levels…
````

**Comment by gottfrois** [comment]
Seems to be working fine with `v3.0.3`

**Comment by maia** [comment]
Unfortunately I'm still having the same problem:
````
> url = "https://www.youtube.com/watch?v=Y45Zq-yKpRw"
 => "https://www.youtube.com/watch?v=Y45Zq-yKpRw"
> lt = LinkThumbnailer.generate(url); lt.title
ArgumentError: string contains null byte
	from …/gems/ruby-2.2.2/gems/oga-1.2.3/lib/oga/xml/lexer.rb:204:in `advance_native'
	from …/gems/ruby-2.2.2/gems/oga-1.2.3/lib/oga/xml/lexer.rb:204:in `block in advance'
	from …/gems/ruby-2.2.2/gems/oga-1.2.3/lib/oga/xml/lexer.rb:147:in `read_data'
	from …/gems/ruby-2.2.2/gems/oga-1.2.3/lib/oga/xml/lexer.rb:203:in `advance'
	from …/gems/ruby-2.2.2/gems/oga-1.2.3/lib/oga/xml/parser.rb:245:in `each_token'
	from …/gems/ruby-2.2.2/gems/oga-1.2.3/lib/oga/xml/parser.rb:282:in `parse'
	from …/gems/ruby-2.2.2/gems/oga-1.2.3/lib/oga/xml/parser.rb:282:in `parse'
	from …/gems/ruby-2.2.2/gems/oga-1.2.3/lib/oga/oga.rb:27:in `parse_html'
	from …/gems/ruby-2.2.2/gems/video_info-2.5.0/lib/video_info/providers/youtube_scraper.rb:91:in `_set_data_from_api'
	from …/gems/ruby-2.2.2/gems/video_info-2.5.0/lib/video_info/provider.rb:32:in `data'
	from …/gems/ruby-2.2.2/gems/video_info-2.5.0/lib/video_info/providers/youtube_scraper.rb:80:in `available?'
	from …/gems/ruby-2.2.2/gems/video_info-2.5.0/lib/video_info/providers/youtube_scraper.rb:68:in `itemprop_node_value'
	from …/gems/ruby-2.2.2/gems/video_info-2.5.0/lib/video_info/providers/youtube_scraper.rb:18:in `duration'
	from …/gems/ruby-2.2.2/gems/link_thumbnailer-3.0.3/lib/link_thumbnailer/video_parser.rb:27:in `duration'
	from …/gems/ruby-2.2.2/gems/link_thumbnailer-3.0.3/lib/link_thumbnailer/models/video.rb:14:in `initialize'
	from …/gems/ruby-2.2.2/gems/link_thumbnailer-3.0.3/lib/link_thumbnailer/scrapers/opengraph/video.rb:29:in `new'
... 29 levels...
````

**Comment by 0mega** [comment]
I started looking into this, and I'm getting an SSL dependency error (I've also tried it with `verify_ssl: false`):

```
2.1.2 :005 > linkt = LinkThumbnailer.generate('https://www.youtube.com/watch?v=liXOb5JXg6w')
Net::HTTP::Persistent::Error: OpenSSL is not available
	from /Users/joanaperrynava/.rvm/gems/ruby-2.1.2/gems/net-http-persistent-2.9.4/lib/net/http/persistent.rb:597:in `connection_for'
	from /Users/joanaperrynava/.rvm/gems/ruby-2.1.2/gems/net-http-persistent-2.9.4/lib/net/http/persistent.rb:994:in `request'
	from /Users/joanaperrynava/.rvm/gems/ruby-2.1.2/gems/link_thumbnailer-3.0.3/lib/link_thumbnailer/processor.rb:54:in `perform_request'
	from /Users/joanaperrynava/.rvm/gems/ruby-2.1.2/gems/link_thumbnailer-3.0.3/lib/link_thumbnailer/processor.rb:27:in `block in call'
	from /Users/joanaperrynava/.rvm/gems/ruby-2.1.2/gems/link_thumbnailer-3.0.3/lib/link_thumbnailer/processor.rb:37:in `with_valid_url'
	from /Users/joanaperrynava/.rvm/gems/ruby-2.1.2/gems/link_thumbnailer-3.0.3/lib/link_thumbnailer/processor.rb:24:in `call'
	from /Users/joanaperrynava/.rvm/gems/ruby-2.1.2/gems/link_thumbnailer-3.0.3/lib/link_thumbnailer/page.rb:17:in `generate'
	from /Users/joanaperrynava/.rvm/gems/ruby-2.1.2/gems/link_thumbnailer-3.0.3/lib/link_thumbnailer.rb:16:in `generate'
	from (irb):5
	from /Users/joanaperrynava/.rvm/rubies/ruby-2.1.2/bin/irb:11:in `<main>'
```

Note: I can use OpenSLL and it's already required in irb where I'm running link_thumbnailer

**Comment by gottfrois** [comment]
Yeah, you are not the only one with this issue https://github.com/gottfrois/link_thumbnailer/issues/67. I should really dig dipper into that SSL issue. Thanks for looking at it

**Comment by 0mega** [comment]
Sorry, didn't see that issue open. I'll try to help with SSL problem during this week.

**Comment by maia** [comment]
gottfrois, do you need any additional feedback regarding the problem with youtube videos? Just asking because the issue still has the "needs feedback" label.

**Comment by gottfrois** [comment]
no thanks @maia I should be able to find what's going on :)

**Comment by aryalsan** [comment]
I am getting the following error. 
```
from -e:1:in `<main>'irb(main):004:0> linkt = LinkThumbnailer.generate('https://www.youtube.com/watch?v=liXOb5JXg6w')
ETHON: started MULTI
ETHON:         performed EASY effective_url=https://i.ytimg.com/vi/liXOb5JXg6w/hqdefault.jpg response_code=200 return_code=write_error total_time=0.878789
ETHON: performed MULTI
ArgumentError: string contains null byte
```

**Comment by 0mega** [comment]
@aryalsan you can use my PR as a workaround while waiting for a fix in video_info gem or maybe even Kernel.open method.

**Comment by aryalsan** [comment]
Any updates coming recently!

**Comment by gottfrois** [comment]
I'm waiting for video_info gem to release their master into a new version :)

**Comment by kurtish** [comment]
We are having the same problems and not of the links to you tube videos are able to generate images.  The weird part is that your thumbnailer demo works fine for your tube, but it is no longer working for us.

**Comment by gottfrois** [comment]
The demo is using this version of LinkThumbnailer https://github.com/gottfrois/link_thumbnailer_api/blob/master/Gemfile.lock#L59

**Comment by kurtish** [comment]
@gottfrois Thanks, is it running on heroku on a Cedar 14 standard build as well?  Just wanted to check as to know if it is the heroku base version of imagemagick being used as well.

**Comment by gottfrois** [comment]
yes it's a standard heroku, nothing fancy. However there are no imagemagick dependency. Where do you see it?

**Comment by aryalsan** [comment]
Still waiting for the updates! Any news yet!!!

**Comment by 0mega** [comment]
@aryalsan this won't be done until [this issue](https://github.com/thibaudgg/video_info/issues/103) is solved so you are welcome to help.

**Comment by idjuradj** [comment]
Hi,

I'm going to write this here, although I'm not sure if it's related to this.

I've set this gem up in my projects, and it works with HTTP links, but it doesn't work with HTTPS.
For example, when I pass a youtube link, I WAS getting this error:
SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed

That error was showing up even if I would set config.verify_ssl = false.

After installing https://gist.github.com/fnichol/867550#file-win_fetch_cacerts-rb, that error went away, but I'm getting the error described in this issue:

"ArgumentError in LinksController#create
string contains null byte"

This happens when I submit youtube links. Other HTTPS links work fine.

Since the demo app uses 3.0.2, should I downgrade to make this work or (I see it working on demo app)?

**Comment by aaronsakowski** [comment]
Still testing, but adding this to the Gemfile works so far for me.

```gem 'video_info', github: 'thibaudgg/video_info'```

Found here: https://github.com/thibaudgg/video_info/issues/100

**Comment by 0mega** [comment]
Hi @idjuradj, you can use my workaround https://github.com/0mega/link_thumbnailer/commit/592309c2710926d90acf25849220dbad2a55bf06, or just rebuild link_thumbnailer locally, pointing to video_info gem master as @aaronsakowski mentioned.

**Comment by gottfrois** [comment]
I'll create a branch that have gemfile points to video_info master branch for you guys

**Comment by gottfrois** [comment]
Use this branch guys, until they release master in a new video_info version https://github.com/gottfrois/link_thumbnailer/tree/tmp-video-info-fix

**Comment by aryalsan** [comment]
Cool, it works for the Youtube video but for Vimeo video, its generates unexpected network error while fetching information about the video

**Comment by 0mega** [comment]
@aryalsan I didn't look into it but it's probably because of the API token that is required to fetch information about the video from vimeo. In version 2.6 of video_info, there will be a vimeo scraper so you won't need an API key.
This does not happen with youtube videos because there is already an implementation of a youtube scraper.

**Comment by maia** [comment]
When using the tmp-video-info-fix branch (and adding gem 'video_info', github: 'thibaudgg/video_info' to Gemfile) parsing youtube videos works. 

Parsing a vimeo.com video generates a "VideoInfo::HttpError: unexpected network error while fetching information about the video" and a "OpenURI::HTTPError: 401 Authorization Required". 

I assume we need to wait for video_info 2.6, @0mega do you have a time frame? Thanks!

**Comment by vheuken** [comment]
@maia There's just one thing left before the 2.6 release. Should be done within 1-2 weeks.

**Comment by gottfrois** [comment]
:+1:

**Comment by aryalsan** [comment]
:+1:

**Comment by aryalsan** [comment]
@vheuken is there any possible dates of the release of Video info gem 2.6

**Comment by vheuken** [comment]
@aryalsan Sorry for the delay. I've been busier than I've expected so I haven't been able to work on it. I'll make some time for it tonight and I should be able to finish it up.

**Comment by aryalsan** [comment]
@vheuken, cool, and we are eagerly waiting for the 2.6 update release. And also would you please check for the Facebook videos, i think its generating the wrong thumbnail URL.

**Comment by vheuken** [comment]
Just implemented most of the last task before 2.6 release. Here's what's left: https://github.com/thibaudgg/video_info/issues/95#issuecomment-160628927

Should be done within a few days.

> And also would you please check for the Facebook videos, i think its generating the wrong thumbnail URL.

video_info doesn't handle Facebook videos

**Comment by gottfrois** [comment]
What's up on this @vheuken ? And happy new year man :)

**Comment by vheuken** [comment]
Sorry, I still have to finish the Vimeo Playlist scraper. If you want, you can try using the branch with the scraper implemented in your project.

`gem 'video_info', :git => 'https://github.com/thibaudgg/video_info', :branch => 'vimeo-scraper'`

**Comment by vheuken** [comment]
Can you guys try the master branch now? Vimeo scraper should be in and we'll push a new version shortly. Sorry for the wait!

**Comment by vheuken** [comment]
video_info 2.6 has been released with the Vimeo scraper. Hopefully this resolves your issue!

**Comment by gottfrois** [comment]
:+1: I will try that when I have a moment :) Thanks for the notice

**Comment by aryalsan** [comment]
Thanks for the release.

**Comment by maia** [comment]
The issue is fixed with video_info `2.6.0` (thanks, @vheuken !). @gottfrois can you push a new version of link_thumbnailer? (plus, there are a few forks that look like they could be pulled in). Thanks everyone!

**Comment by gottfrois** [comment]
Released in `v3.1.1`. Thanks every one to make it happen :)

**Comment by vheuken** [comment]
Please keep in mind that, due to the nature of scrapers, future breakage is a very real possibility. If you ever have an issue I'll be more than happy to release a patch fix.

**Comment by gottfrois** [comment]
Of course, thanks for the reminder. What are our options to limit them? Using each provider APIs directly I imagine?

**Comment by vheuken** [comment]
I think you should point out to users that they are able to set a Vimeo API key as follows:

`VideoInfo.provider_api_keys = { vimeo: 'YOUR_VIMEO_API_KEY' }`

(Of course, you are free to make your own interface around that).

**Comment by gottfrois** [comment]
Right, I'll probably include that in the gem config

**Comment by vheuken** [comment]
Just a heads up, we're getting ready for a 2.7 release in the coming weeks where we [significantly reduced our gem dependencies](https://github.com/thibaudgg/video_info/issues/116#issuecomment-191472266), so it will probably be a good idea to update to that when we release that. I'll try to ping you or send over a PR when it's ready. I'm sure your users will appreciate having to pull in a few fewer gems.

**Comment by gottfrois** [comment]
@vheuken sounds great :)
