### ISSUE TITLE
link_thumbnailer fetching descriptions from <p> in wrong order 

### ISSUE THREAD

**Issue by aruprakshit** [gottfrois/link_thumbnailer#74]
Hello,

I am not sure if it is a issue or something else. In our production when we are giving this link : 
http://www.divorceforce.com/article/288-divorce-case-law-autistic-child-support-and-custody , it is not able to fetch the description from the `<p>` which comes first. It is scrapping the description from the `<p>` which comes last in the document order.

I read this - 
https://github.com/gottfrois/link_thumbnailer/wiki/Attributes-option-explained#description. Thus expecting it to scrape -- "
When parents of special needs children divorce, the term "best interests of the child" becomes espe..", but it is fetching text from `<p>` which are below in the document order.

Can you give some hints where it is wrong ?

**Comment by gottfrois** [comment]
I've released the possibility to customize graders weight. I've given 3 times more weight to the position grader. While it will not fix this particular case, it should give more accurate results. If you really want full control, you can create your own grader or disable the length grader here https://github.com/gottfrois/link_thumbnailer/blob/cb48ef3cbd22a1eb041cf254a7bf146d0158885c/lib/link_thumbnailer/configuration.rb#L50

More info on how to create your own grader can be found here https://github.com/gottfrois/link_thumbnailer/wiki/How-to-build-your-own-Grader%3F
