### ISSUE TITLE
Rails LinkThumbnailer returns null for Youtube Video URL

### ISSUE THREAD

**Issue by aryalsan** [gottfrois/link_thumbnailer#75]
I am using to LinkThumbnailer gem in my program. It works for every links but whenever I provide the Youtube video URL it returns

```
ArgumentError in ContentController#index
string contains null byte
Please help me to fix it.
```

I am using @object = LinkThumbnailer.generate(params[:weblink]) in my controller and
```
@object.title
@object.images
@object.description
```
in my view to fetch the LinkThumbnailer data.

**Comment by lavika** [comment]
Is the issue fixed? I am still facing it.

**Comment by gottfrois** [comment]
See this issue https://github.com/gottfrois/link_thumbnailer/issues/69
