### ISSUE TITLE
Error install ???

### ISSUE THREAD

**Issue by ks0lo** [gottfrois/link_thumbnailer#77]
I have this problem when i put command rails g link_thumbnailer:install
http://i.imgur.com/ZTgqWOr.jpg

i try to put by hand link_thumbnailer.rb file and when i go in irb console to put require 'link_thumbnailer' give me this ? 
http://i.stack.imgur.com/uCVoD.jpg

I'm new in rails dev. and when i fix this bug i don't understand next step

**Comment by gottfrois** [comment]
Hey there,

I haven't tested the gem on windows :-/ Doing ruby/rails on windows is generally not a good idea. You will find yourself in trouble many times since gems are not always windows ready. Anyway, can you copy paste the entire stack trace? Since from your screenshot I can't see the beginning where the real issue is ;)

**Comment by ks0lo** [comment]
http://i.imgur.com/mNuWvwx.jpg

**Comment by gottfrois** [comment]
right, so the gem need the `curl` library to work properly. I'm afraid it's not installed on your machine. I have no idea how to install it on a window so you will need to look for it i'm afraid.

**Comment by ks0lo** [comment]
i fix the curl library but now i don't understand how to use the gem in views file, controller ...  i looked the demo repository, but i can't understand angular sintax and how it's work everything. Can you make simple scaffold app with the basic usage ? Thanks

**Comment by gottfrois** [comment]
```ruby
class ThumbnailsController
  def new
    @object = LinkThumbnailer.generate(params[:url])

     render :new
  end
end
```

Go to http://localhost:3000/thumbnails/new?url=http://foo.com

In your view you can access website info by using `@object`. Ex:

```ruby
@object.title
@object.description
@object.images.first.url
```

**Comment by ks0lo** [comment]
I can't understand how to work with this 
Sorry for stupid questions i use rails from 2 month and obviously i'm beginner
look this repository https://github.com/ks0lo/linkgo
What i need to add to work this gem

**Comment by gottfrois** [comment]
Run this command: `bundle exec rails g controller thumbnails new`. It will create a bunch of files. Open `app/controllers/thumbnails_controller.rb` and make it look like this:

```
class ThumbnailsController < ApplicationController
  def new
    @object = LinkThumbnailer.generate(params[:url])
  end
end
```

Edit `app/views/thumbnails/new.html.erb` and add this:

```
<%= @object.title %>
<%= @object.description %>
```

Launch your rails server: `bundle exec rails s` and go to [http://localhost:3000/thumbnails/new?url=http://foo.com](http://localhost:3000/thumbnails/new?url=http://foo.com)

**Comment by ks0lo** [comment]
i put this code the first time but i can figure out how to implement this code in the real app with the input form, save to database, proper work with devise gem,  execute the thumbnail in index page

**Comment by gottfrois** [comment]
you are almost there :) keep digging ! I can't help you more than that without actually doing it for you ;)
