### ISSUE TITLE
link_thumbnailer recognized as browser with AdBlock/uBlock enabled

### ISSUE THREAD

**Issue by avandrel** [gottfrois/link_thumbnailer#81]
When I try to thumbnail articles on polish newspaper site 'wyborcza.pl', link_thumbnailer is recognized as browser with AdBlock/uBlock enabled. In irb I can execute:

```
page = LinkThumbnailer.generate("http://wroclaw.wyborcza.pl/wroclaw/1,35771,19481129,razem-krytykuje-esk-i-chce-audytu-finansowego-i-artystycznego.html")
```

to get:

```
#<LinkThumbnailer::Models::Website:0x00000002f035a0 @images=[#<LinkThumbnailer::Models::Image:0x00000002de94f8 @src=#<URI::HTTP:0x00000002eecc10 URL:http://bi.gazeta.pl/im/3/17117/m17117193.png>, @size=[212, 70], @type=:png>], @videos=[], @url=#<URI::HTTP:0x00000002f154a8 URL:http://wroclaw.wyborcza.pl/wroclaw/1,35771,19481129,razem-krytykuje-esk-i-chce-audytu-finansowego-i-artystycznego.html?disableRedirects=true>, @title="Wyborcza.pl", @description="Aby czytać nasze artykuły wyłącz AdBlocka/uBlocka lub dodaj wyjątek dla naszej domeny - zobacz jak to zrobić.", @favicon=""> 
```

description field states: 'To read our article please disable AdBlock/uBlock or add exception to for out domain'. Title field is also missing. If you use this address in browser everything seems to be alright (even with AdBlock enabled).

**Comment by gottfrois** [comment]
Have you tried playing with the `user-agent`? By default the user-agent is set to `link_thumbnailer`, maybe you should try a real browser user-agent.

**Comment by avandrel** [comment]
Yup, that was it. Browser's user-agent still got me no response, but robot's user-agent got it to work. Thank you very much.

**Comment by gottfrois** [comment]
Awesome :)
