### ISSUE TITLE
misleading project name / description 

### ISSUE THREAD

**Issue by jm3** [gottfrois/link_thumbnailer#83]
Hi! I don't mean to be a downer, but I think the name and description of the project is really misleading. This doesn't "generate" (create) thumbnails from links or websites, as the name and readme implies. Rather, it DOWNLOADS pre-existing images associated with a website, using oembed, etc. Those are two very different things.

A project for generating thumbnails of websites will load the website in a virtual framebuffer or browser, and capture an actual image of the page. There are projects that do this.

It's not to say that one is better than the other, just that this project should describe itself as something more like thumbnail metadata downloader, or something like that, not a thumbnail _generator_, so as not to mislead people.

My personal opinion, I don't think you're trying to intentionally confuse people, just that it wasn't the best way to describe. :)

**Comment by gottfrois** [comment]
I think you are right :) Would you have a description to propose maybe?

**Comment by jm3** [comment]
@gottfrois hm, how about **Metadata Fetcher**?

**Comment by iroth** [comment]
@gottfrois I would propose **WebPageSummary** or **LinkSummary**
but anyway, thanks for the contribution - this is super useful for us!

**Comment by gottfrois** [comment]
Thanks for the suggestions, I'm afraid I won't be able to change the gem name. I was thinking gem's description.

Thanks @iroth ;)

**Comment by gottfrois** [comment]
I've updated the gem description. Changing the gem name is just too much work and would break compatibility.
Thanks for you feedback folks!
