### ISSUE TITLE
some URLs fail when using LinkThumbnailer Gem

### ISSUE THREAD

**Issue by iroth** [gottfrois/link_thumbnailer#84]
this URL fails with 404, but when used in the demo app it works:
https://medium.com/greylock-perspectives/the-hierarchy-of-engagement-5803bf4e6cfa#.3r7b2tdbd

**Comment by gottfrois** [comment]
Seems to work with latest version:

> o = LinkThumbnailer.generate('https://medium.com/greylock-perspectives/the-hierarchy-of-engagement-5803bf4e6cfa#.clk9zccuq')
> o.title
 => "The Hierarchy of Engagement — Greylock Perspectives"
> LinkThumbnailer::VERSION
 => "3.1.1"

**Comment by iroth** [comment]
Hi @gottfrois, I have the latest version and I get a 404 not found error. Here is my config:
  config.redirect_limit = 5
  config.verify_ssl = false
  config.http_open_timeout = 5
  config.description_min_length = 35
  config.positive_regex = /article|body|content|entry|hentry|main|page|pagination|post|text|blog|story/i
  config.negative_regex = /combx|comment|com-|contact|foot|footer|footnote|masthead|media|meta|outbrain|promo|related|scroll|shoutbox|sidebar|sponsor|shopping|tags|tool|widget|modal/i
  config.raise_on_invalid_format = false

and the call itself:

        object = LinkThumbnailer.generate(uri, verify_ssl: false)

note: I guess I do not need to pass verify_ssl, but even if I take it down or change the config to true, I get the error.

If I pass the URL ommitting the #... at the end, it works fine

**Comment by gottfrois** [comment]
hm, what ruby version are you using?

**Comment by iroth** [comment]
ruby 2.2.1
rails 4.2.2

**Comment by gottfrois** [comment]
Still having the issue?

**Comment by Brotakuu** [comment]
Keep getting `OpenSSL::SSL::SSLError (SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed)`

**Comment by gottfrois** [comment]
Closing this issue since i was not able to reproduce
