### ISSUE TITLE
Make the description length configurable to an arbitrary length.

### ISSUE THREAD

**Issue by shenders13** [gottfrois/link_thumbnailer#85]
The upside down gaussian function in the LinkThumbnailer gem is centred at 120. It would be fantastic to generalise the gem so the user can specify where the gaussian function cuts the x axis - making the description length the gem returns customisable.

**Comment by gottfrois** [comment]
As promised :) Available in `v3.1.2`:

Allows to customize ideal description length

Pass the :ideal_description_length option to the Graders::Length initializer to customize
the ideal description length of a website. In the rails initializer:

```ruby
LinkThumbnailer.configure do |config|
  config.graders = [
    ->(description) { ::LinkThumbnailer::Graders::Length.new(description, ideal_description_length: 500) },
    ->(description) { ::LinkThumbnailer::Graders::HtmlAttribute.new(description, :class) },
    ->(description) { ::LinkThumbnailer::Graders::HtmlAttribute.new(description, :id) },
    ->(description) { ::LinkThumbnailer::Graders::Position.new(description, weigth: 3) },
    ->(description) { ::LinkThumbnailer::Graders::LinkDensity.new(description) },
  ]
end
```

Will default to `120` characters. More information about how the gem manage to find the best description can be found at
http://www.codeids.com/2015/06/27/how-to-find-best-description-of-a-website-using-linkthumbnailer/
