### ISSUE TITLE
Ideal Description Length functionality not working.

### ISSUE THREAD

**Issue by shenders13** [gottfrois/link_thumbnailer#87]
Say I pick an arbitrary news article, say:

_http://www.nytimes.com/2016/05/02/us/politics/indiana-primary-ted-cruz-donald-trump.html?hp&action=click&pgtype=Homepage&clickSource=story-heading&module=first-column-region&region=top-news&WT.nav=top-news_

And configure the ideal description length to be 800 characters in my linkthumbnailer.rb initialiser as below:

_LinkThumbnailer.configure do |config|
  config.graders = [
    ->(description) { ::LinkThumbnailer::Graders::Length.new(description, ideal_description_length: 800) },
    ->(description) { ::LinkThumbnailer::Graders::HtmlAttribute.new(description, :class) },
    ->(description) { ::LinkThumbnailer::Graders::HtmlAttribute.new(description, :id) },
    ->(description) { ::LinkThumbnailer::Graders::Position.new(description) },
    ->(description) { ::LinkThumbnailer::Graders::LinkDensity.new(description) },
  ]
end_

 If I then run LinkThumbnailer, say in the console:

_LinkThumnailer.generate("http://www.nytimes.com/2016/05/02/us/politics/indiana-primary-ted-cruz-donald-trump.html?hp&action=click&pgtype=Homepage&clickSource=story-heading&module=first-column-region&region=top-news&WT.nav=top-news")_

It will return a description with length 168, which is significantly shorter than the specified 800.

As an FYI, the exact description in pull is:

_@description="Two days before what is widely viewed as a must-win primary for Mr. Cruz, a poll showed Donald J. Drumpf with a lead of 15 points among likely Republican primary voters."_

**Comment by gottfrois** [comment]
The issue is that the site above use the html `description` meta attribute to tell the world what this article is about http://d.pr/i/EpMl

LinkThumbnailer look for this meta attributes among others (http://ogp.me/) and prioritize them if they are found on the webpage. Only if it failed, it will use its internal description parser to "guess" the best description using the Graders you have configured.

**Comment by gottfrois** [comment]
In version `v3.2.0` you can disable the `opengraph` scraping strategy. Allowing to only use the homemade strategy to scrap your websites.

See the [changelog](https://github.com/gottfrois/link_thumbnailer/blob/master/CHANGELOG.md#320) for more information.
