### ISSUE TITLE
Some sites throw RedirectLimit error.

### ISSUE THREAD

**Issue by shenders13** [gottfrois/link_thumbnailer#95]
The Daily Telegraph, Courier Mail, and Fox Sport's websites don't work for LinkThumbnailer. They throw a RedirectLimit error.

See the links below: 

- http://www.dailytelegraph.com.au/technology/sydney-wild-weather-homes-at-risk-as-collaroy-narrabeen-battered-by-storm/news-story/45e63ecdca3e9678f51ac51270996781
- http://www.couriermail.com.au/news/queensland/police-declare-emergency-situation-at-elizabeth-street-woodend/news-story/914f6a0ab1ccc23aa8136280a938f551
- http://www.foxsports.com.au/football/premier-league/jamie-vardy-to-arsenal-striker-will-decide-leicester-future-before-leaving-for-france-with-england/news-story/90b9072963f2b2cde6cbeea2ce3c07e5

Is this fixable?

Best regards, Sam

**Comment by gottfrois** [comment]
Of course, this is something you can configure yourself using:

```ruby
LinkThumbnailer.generate('http://...', redirect_limit: 10)
```

or globaly:

```ruby
LinkThumbnailer.configure do |config|
  config.redirect_limit = 10
end
```

**Comment by umamaheswari-raj** [comment]
@gottfrois  Still I am facing the issue while passing twitter share url after I mention the redirect_limit is equal to 10. can u help me?

**Comment by gottfrois** [comment]
Have you tried to increase the `redirect_limit` by a lot to see if you are in an infinite redirect loop or just the origin website redirects a lot of times before serving the content?
