### ISSUE TITLE
Gem "link_thumbnailer" install issue

### ISSUE THREAD

**Issue by arunnura** [gottfrois/link_thumbnailer#99]
Hi,
we are trying to install this interesting gem, though we encountered a strange issue with ruby version. Can you please advise?

Error details:

Our server ruby version:  2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux-gnu]
Command:  "gem install link_thumbnailer"
ERROR:  Error installing link_thumbnailer:
        activesupport requires Ruby version >= 2.2.2.

Thanks in advance.

**Comment by gottfrois** [comment]
hm are you sure you have the proper ruby version loaded?

> gem install link_thumbnailer
Fetching: link_thumbnailer-3.2.1.gem (100%)
Successfully installed link_thumbnailer-3.2.1
Parsing documentation for link_thumbnailer-3.2.1
Installing ri documentation for link_thumbnailer-3.2.1
Done installing documentation for link_thumbnailer after 0 seconds
1 gem installed
> ruby -v
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]

**Comment by gottfrois** [comment]
Solved your issue? Closing but feel free to ping me if it's something related to the gem.
